# Meta Data for SEO

## Homepage
title = "SparkERP"
titleSeparator = ""
titleAddition = ""
description = ""

## Open Graph + Twitter Cards
images = ["tech.jpg"]
twitterSite = "henkverlinde"
twitterCreator = "henkverlinde"
facebookAuthor = "verlinde.henk"
facebookPublisher = "verlinde.henk"
ogLocale = "en_US"

## JSON-LD
schemaType = "Organization"
schemaLogo = "logo-doks.png"
schemaTwitter = "https://twitter.com/"
schemaLinkedIn = "https://www.linkedin.com/in/"
schemaGitHub = "https://github.com/"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Powered by Spark Technology Corp"

# Alert
alert = false
alertText = "Thanks"

# Edit Page
docsRepo = "https://github.com/"
editPage = false

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  darkMode = true
  bootStrapJs = false
  breadCrumb = false
  highLight = true
  kaTex = false
